#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AppAction {
    Quit,
    Help,
    HealthCheckPrompt,
    RunSelected,
    OpenShell,
    Terminate,
    SetDefault,
    UnregisterPrompt,
    ShutdownPrompt,
    ExportPrompt,
    ImportPrompt,
    MoveSelection(isize),
    Ignore,
    CustomActionsPrompt,
    SearchPrompt,
    ClearSearch,
    TogglePin,
    ToggleMultiSelect,
    ClonePrompt,
    RollBackPrompt,
    SnapshotPrompt,
    SnapshotManagerPrompt,
    OpenCatalogPrompt,
}
