mod actions;
mod components;
mod controller;
pub mod diagnostics;
pub mod keymaps;
mod reducers;
pub mod snapshots;
mod state;
pub mod worker;
pub use controller::run_tui;
pub use state::{AppState, Modal};
